// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ServerApp.Model;
using System;

namespace ServerApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210716102625_candidateInfotable")]
    partial class candidateInfotable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServerApp.Model.AdminInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Username");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ServerApp.Model.CandidateInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ElectionName");

                    b.Property<string>("Name");

                    b.Property<string>("Symbol");

                    b.HasKey("id");

                    b.ToTable("CandidateInfos");
                });

            modelBuilder.Entity("ServerApp.Model.Vote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("NID");

                    b.Property<string>("Symbol");

                    b.HasKey("id");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ServerApp.Model.VoterInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<long>("NID");

                    b.HasKey("id");

                    b.ToTable("Voters");
                });
#pragma warning restore 612, 618
        }
    }
}
